app:
  name: familycloud
  host: 0.0.0.0
  port: 5050
  log_level: info
  log_directory: ./familycloud_logs
database:
  name: familycloud
  host: localhost
  port: 5432
  user_name: allawiii
  password: 0788
email:
  protocol: "smtp" # if smtps = no need for tls_required , if smtp and not mailhog tls_required = true
  tls_param: false
  port: 1025
  server: localhost
  username: anything
  password: anything
  from_sender: noreply@yourapp.com
rustfs:
  region: us-east-1
  access_key: family
  url: http://127.0.0.1:9000
secrets:
  rustfs: OIodbFUiNK34xthjR0newczMC6HaAyksJS1GXfYZ
  hmac: OIodbFUiNK34xthjR0newczMC6HaAyksJS1GXfYZ
redis:
  host: 127.0.0.1
  port: 6379
token_options:
  max_concurrent_download: 10
  download_token_ttl: 1440 # 1day
  change_email_token: 10 # 10 minutes
  refresh_token: 43200 # 30 days
  jwt_token: 15 # 15 minutes
  password_reset_token: 5 # 5 minutes
  signup_token: 5 # 5 minutes
